python gpu.py 0 &
python gpu.py 1 &
python gpu.py 2 &
python gpu.py 3 &
python gpu.py 4 &
python gpu.py 5 &
python gpu.py 6 &
python gpu.py 7 &
python gpu.py 8 &
python gpu.py 9 &
python gpu.py 10 &
python gpu.py 11 &
python gpu.py 12 &
python gpu.py 13 &
python gpu.py 14 &
python gpu.py 15 &
